### ISSUE TITLE
is doc wrong?

### ISSUE THREAD

**Issue by PSLLSP** [VCTLabs/cp210x-program#1]
```
<h3>Read EEPROM content into hexfile:</h3>
<pre>$ cp210x-program --read-cp210x -F eeprom-content.hex
```
Is this correct? I think it should be in this way (because -F reads from file and -f writes to file):

```
<h3>Read EEPROM content into hexfile:</h3>
<pre>$ cp210x-program --read-cp210x -f eeprom-content.hex
```

I see this error in files README and doc/index.html.

**Comment by PSLLSP** [comment]
Other problem, what is the source of your ID 10c4:ea62 in the "write" example? CP2102 has USB ID 10c4:ea60.

https://www.silabs.com/documents/public/data-sheets/CP2102-9.pdf

**Comment by SJLC** [comment]
> ```
> <h3>Read EEPROM content into hexfile:</h3>
> <pre>$ cp210x-program --read-cp210x -F eeprom-content.hex
> ```
> 
> Is this correct? I think it should be in this way (because -F reads from file and -f writes to file):
> 
> ```
> <h3>Read EEPROM content into hexfile:</h3>
> <pre>$ cp210x-program --read-cp210x -f eeprom-content.hex
> ```
> 
> I see this error in files README and doc/index.html.

That does look like an error, thanks for reporting.

> Other problem, what is the source of your ID 10c4:ea62 in the "write" example? CP2102 has USB ID 10c4:ea60.
> 
> https://www.silabs.com/documents/public/data-sheets/CP2102-9.pdf

This one is not an error, there are different devices made by different vendors covered by cp210x and some of them have different product IDs. The '-m' option gives the ability match non-standard IDs, of which 10c4:ea62 has specifically been seen in the field (e.g. https://www.silabs.com/community/interface/forum.topic.html/esp32-lyratd-msccp2-WhIN ) and is thus a good example.
